name: Deploy Anomaly Detection Service to Cloud Run

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PROJECT_ID: unique-spirit-469000-h2
  REGION: us-central1
  SERVICE_NAME: anomaly-detection-service
  REPO_NAME: anomaly-detection-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'   # ✅ Required for GitHub OIDC → GCP Workload Identity Federation

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Verify JAR files
      - name: List JAR files
        run: ls -lh target

      # 🔎 Debug GitHub OIDC Token
      - name: Debug GitHub OIDC Token
        id: oidc
        run: |
          echo "Fetching OIDC token..."
          ID_TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                        "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.googleapis.com" | jq -r .value)
          echo "OIDC Token: $ID_TOKEN"

          echo "Decoding payload..."
          PAYLOAD=$(echo $ID_TOKEN | cut -d "." -f2 | base64 -d 2>/dev/null | jq .)
          echo "Decoded payload: $PAYLOAD"

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/940370294638/locations/global/workloadIdentityPools/github-pool-2/providers/github-provider-2
          service_account: github-actions-deployer@unique-spirit-469000-h2.iam.gserviceaccount.com

      # Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
                       -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:latest .

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:latest

      # Deploy to Cloud Run,
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:latest \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated
